'use client'

import React, { createContext, useContext, useState } from 'react'
import { Language, Translations, defaultTranslations, languageNames } from '@/lib/i18n/translations'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: Translations
  languageName: string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Simple translations for all languages
const translations: Record<Language, Translations> = {
  de: { siteName: 'Weltverfassung', tagline: 'Eine Verfassung für die Menschheit', vote: 'Abstimmen', yes: 'Ja', no: 'Nein', abstain: 'Enthaltung', visitors: 'Besucher', countries: 'Länder', comments: 'Kommentare', languages: 'Sprachen', share: 'Teilen', download: 'Herunterladen', donate: 'Spenden', learnMore: 'Mehr erfahren', participate: 'Mitmachen', privacy: 'Datenschutz', imprint: 'Impressum', acceptCookies: 'Akzeptieren', cookieNotice: 'Wir nutzen Cookies.', newsletter: 'Newsletter', yourEmail: 'E-Mail', subscribe: 'Anmelden', readConstitution: 'Verfassung lesen', supportMission: 'Mission unterstützen', spreadWord: 'Weitersagen', joinDiscussion: 'Diskutieren', helpTranslate: 'Übersetzen', becomeAdvocate: 'Fürsprechen', educateOthers: 'Bildung', donateNow: 'Spenden', getInvolved: 'Engagieren', organize: 'Organisieren' },
  en: { siteName: 'World Constitution', tagline: 'A Constitution for Humanity', vote: 'Vote', yes: 'Yes', no: 'No', abstain: 'Abstain', visitors: 'Visitors', countries: 'Countries', comments: 'Comments', languages: 'Languages', share: 'Share', download: 'Download', donate: 'Donate', learnMore: 'Learn More', participate: 'Participate', privacy: 'Privacy', imprint: 'Imprint', acceptCookies: 'Accept', cookieNotice: 'We use cookies.', newsletter: 'Newsletter', yourEmail: 'Email', subscribe: 'Subscribe', readConstitution: 'Read Constitution', supportMission: 'Support Mission', spreadWord: 'Spread Word', joinDiscussion: 'Discuss', helpTranslate: 'Translate', becomeAdvocate: 'Advocate', educateOthers: 'Educate', donateNow: 'Donate', getInvolved: 'Get Involved', organize: 'Organize' },
  es: { siteName: 'Constitución Mundial', tagline: 'Una Constitución para la Humanidad', vote: 'Votar', yes: 'Sí', no: 'No', abstain: 'Abstenerse', visitors: 'Visitantes', countries: 'Países', comments: 'Comentarios', languages: 'Idiomas', share: 'Compartir', download: 'Descargar', donate: 'Donar', learnMore: 'Más info', participate: 'Participar', privacy: 'Privacidad', imprint: 'Aviso legal', acceptCookies: 'Aceptar', cookieNotice: 'Usamos cookies.', newsletter: 'Boletín', yourEmail: 'Email', subscribe: 'Suscribir', readConstitution: 'Leer Constitución', supportMission: 'Apoyar Misión', spreadWord: 'Difundir', joinDiscussion: 'Discutir', helpTranslate: 'Traducir', becomeAdvocate: 'Defender', educateOthers: 'Educar', donateNow: 'Donar', getInvolved: 'Participar', organize: 'Organizar' },
  fr: { siteName: 'Constitution Mondiale', tagline: 'Une Constitution pour l\'Humanité', vote: 'Voter', yes: 'Oui', no: 'Non', abstain: 'S\'abstenir', visitors: 'Visiteurs', countries: 'Pays', comments: 'Commentaires', languages: 'Langues', share: 'Partager', download: 'Télécharger', donate: 'Donner', learnMore: 'En savoir plus', participate: 'Participer', privacy: 'Confidentialité', imprint: 'Mentions légales', acceptCookies: 'Accepter', cookieNotice: 'Nous utilisons des cookies.', newsletter: 'Newsletter', yourEmail: 'Email', subscribe: 'S\'abonner', readConstitution: 'Lire Constitution', supportMission: 'Soutenir Mission', spreadWord: 'Partager', joinDiscussion: 'Discuter', helpTranslate: 'Traduire', becomeAdvocate: 'Défendre', educateOthers: 'Éduquer', donateNow: 'Donner', getInvolved: 'S\'impliquer', organize: 'Organiser' },
  it: { siteName: 'Costituzione Mondiale', tagline: 'Una Costituzione per l\'Umanità', vote: 'Vota', yes: 'Sì', no: 'No', abstain: 'Astenersi', visitors: 'Visitatori', countries: 'Paesi', comments: 'Commenti', languages: 'Lingue', share: 'Condividi', download: 'Scarica', donate: 'Dona', learnMore: 'Scopri di più', participate: 'Partecipa', privacy: 'Privacy', imprint: 'Impronta', acceptCookies: 'Accetta', cookieNotice: 'Usiamo i cookie.', newsletter: 'Newsletter', yourEmail: 'Email', subscribe: 'Iscriviti', readConstitution: 'Leggi Costituzione', supportMission: 'Sostieni Missione', spreadWord: 'Diffondi', joinDiscussion: 'Discuti', helpTranslate: 'Traduci', becomeAdvocate: 'Difendi', educateOthers: 'Educa', donateNow: 'Dona', getInvolved: 'Coinvolgiti', organize: 'Organizza' },
  pt: { siteName: 'Constituição Mundial', tagline: 'Uma Constituição para a Humanidade', vote: 'Votar', yes: 'Sim', no: 'Não', abstain: 'Abster-se', visitors: 'Visitantes', countries: 'Países', comments: 'Comentários', languages: 'Idiomas', share: 'Compartilhar', download: 'Baixar', donate: 'Doar', learnMore: 'Saiba mais', participate: 'Participar', privacy: 'Privacidade', imprint: 'Impressão', acceptCookies: 'Aceitar', cookieNotice: 'Usamos cookies.', newsletter: 'Newsletter', yourEmail: 'Email', subscribe: 'Inscrever', readConstitution: 'Ler Constituição', supportMission: 'Apoiar Missão', spreadWord: 'Divulgar', joinDiscussion: 'Discutir', helpTranslate: 'Traduzir', becomeAdvocate: 'Defender', educateOthers: 'Educar', donateNow: 'Doar', getInvolved: 'Envolver-se', organize: 'Organizar' },
  ru: { siteName: 'Всемирная Конституция', tagline: 'Конституция для Человечества', vote: 'Голосовать', yes: 'Да', no: 'Нет', abstain: 'Воздержаться', visitors: 'Посетители', countries: 'Страны', comments: 'Комментарии', languages: 'Языки', share: 'Поделиться', download: 'Скачать', donate: 'Пожертвовать', learnMore: 'Узнать больше', participate: 'Участвовать', privacy: 'Конфиденциальность', imprint: 'Импринт', acceptCookies: 'Принять', cookieNotice: 'Мы используем куки.', newsletter: 'Рассылка', yourEmail: 'Email', subscribe: 'Подписаться', readConstitution: 'Читать Конституцию', supportMission: 'Поддержать Миссию', spreadWord: 'Распространить', joinDiscussion: 'Обсудить', helpTranslate: 'Перевести', becomeAdvocate: 'Защищать', educateOthers: 'Обучать', donateNow: 'Пожертвовать', getInvolved: 'Включиться', organize: 'Организовать' },
  zh: { siteName: '世界宪法', tagline: '人类宪法', vote: '投票', yes: '赞成', no: '反对', abstain: '弃权', visitors: '访客', countries: '国家', comments: '评论', languages: '语言', share: '分享', download: '下载', donate: '捐赠', learnMore: '了解更多', participate: '参与', privacy: '隐私', imprint: '法律声明', acceptCookies: '接受', cookieNotice: '我们使用Cookie。', newsletter: '通讯', yourEmail: '邮箱', subscribe: '订阅', readConstitution: '阅读宪法', supportMission: '支持使命', spreadWord: '传播', joinDiscussion: '讨论', helpTranslate: '翻译', becomeAdvocate: '倡导', educateOthers: '教育', donateNow: '捐赠', getInvolved: '参与', organize: '组织' },
  ja: { siteName: '世界憲法', tagline: '人類のための憲法', vote: '投票', yes: '賛成', no: '反対', abstain: '棄権', visitors: '訪問者', countries: '国', comments: 'コメント', languages: '言語', share: '共有', download: 'ダウンロード', donate: '寄付', learnMore: '詳細', participate: '参加', privacy: 'プライバシー', imprint: 'インプリント', acceptCookies: '同意', cookieNotice: 'Cookieを使用します。', newsletter: 'ニュースレター', yourEmail: 'メール', subscribe: '購読', readConstitution: '憲法を読む', supportMission: 'ミッションを支援', spreadWord: '広める', joinDiscussion: '議論', helpTranslate: '翻訳', becomeAdvocate: '提唱', educateOthers: '教育', donateNow: '寄付', getInvolved: '参加', organize: '組織' },
  ko: { siteName: '세계 헌법', tagline: '인류를 위한 헌법', vote: '투표', yes: '찬성', no: '반대', abstain: '기권', visitors: '방문자', countries: '국가', comments: '댓글', languages: '언어', share: '공유', download: '다운로드', donate: '기부', learnMore: '더보기', participate: '참여', privacy: '개인정보', imprint: '법적고지', acceptCookies: '수락', cookieNotice: '쿠키를 사용합니다.', newsletter: '뉴스레터', yourEmail: '이메일', subscribe: '구독', readConstitution: '헌법 읽기', supportMission: '미션 지원', spreadWord: '전파', joinDiscussion: '토론', helpTranslate: '번역', becomeAdvocate: '옹호', educateOthers: '교육', donateNow: '기부', getInvolved: '참여', organize: '조직' },
  ar: { siteName: 'الدستور العالمي', tagline: 'دستور للبشرية', vote: 'صوّت', yes: 'نعم', no: 'لا', abstain: 'امتناع', visitors: 'زوار', countries: 'دول', comments: 'تعليقات', languages: 'لغات', share: 'شارك', download: 'تحميل', donate: 'تبرع', learnMore: 'المزيد', participate: 'شارك', privacy: 'الخصوصية', imprint: 'القانوني', acceptCookies: 'قبول', cookieNotice: 'نستخدم ملفات تعريف الارتباط.', newsletter: 'النشرة', yourEmail: 'البريد', subscribe: 'اشترك', readConstitution: 'اقرأ الدستور', supportMission: 'ادعم المهمة', spreadWord: 'انشر', joinDiscussion: 'ناقش', helpTranslate: 'ترجم', becomeAdvocate: 'ادعُ', educateOthers: 'علّم', donateNow: 'تبرع', getInvolved: 'انخرط', organize: 'نظّم' },
  hi: { siteName: 'विश्व संविधान', tagline: 'मानवता के लिए संविधान', vote: 'वोट करें', yes: 'हाँ', no: 'नहीं', abstain: 'वोट नहीं', visitors: 'आगंतुक', countries: 'देश', comments: 'टिप्पणियाँ', languages: 'भाषाएँ', share: 'साझा करें', download: 'डाउनलोड', donate: 'दान करें', learnMore: 'और जानें', participate: 'भाग लें', privacy: 'गोपनीयता', imprint: 'कानूनी', acceptCookies: 'स्वीकार करें', cookieNotice: 'हम कुकीज़ का उपयोग करते हैं।', newsletter: 'समाचार पत्र', yourEmail: 'ईमेल', subscribe: 'सदस्यता', readConstitution: 'संविधान पढ़ें', supportMission: 'मिशन का समर्थन करें', spreadWord: 'फैलाएं', joinDiscussion: 'चर्चा करें', helpTranslate: 'अनुवाद करें', becomeAdvocate: 'वकील बनें', educateOthers: 'शिक्षित करें', donateNow: 'दान करें', getInvolved: 'शामिल हों', organize: 'आयोजित करें' },
  bn: { siteName: 'বিশ্ব সংবিধান', tagline: 'মানবতার জন্য সংবিধান', vote: 'ভোট দিন', yes: 'হ্যাঁ', no: 'না', abstain: 'বর্জন', visitors: 'দর্শনার্থী', countries: 'দেশ', comments: 'মন্তব্য', languages: 'ভাষা', share: 'শেয়ার', download: 'ডাউনলোড', donate: 'দান', learnMore: 'আরও জানুন', participate: 'অংশগ্রহণ', privacy: 'গোপনীয়তা', imprint: 'আইনি', acceptCookies: 'গ্রহণ', cookieNotice: 'আমরা কুকিজ ব্যবহার করি।', newsletter: 'নিউজলেটার', yourEmail: 'ইমেইল', subscribe: 'সাবস্ক্রাইব', readConstitution: 'সংবিধান পড়ুন', supportMission: 'মিশন সমর্থন', spreadWord: 'ছড়িয়ে দিন', joinDiscussion: 'আলোচনা', helpTranslate: 'অনুবাদ', becomeAdvocate: 'সমর্থন', educateOthers: 'শিক্ষা', donateNow: 'দান', getInvolved: 'জড়িত', organize: 'সংগঠিত' },
  tr: { siteName: 'Dünya Anayasası', tagline: 'İnsanlık için Bir Anayasa', vote: 'Oy Ver', yes: 'Evet', no: 'Hayır', abstain: 'Çekimser', visitors: 'Ziyaretçi', countries: 'Ülke', comments: 'Yorum', languages: 'Dil', share: 'Paylaş', download: 'İndir', donate: 'Bağış', learnMore: 'Daha Fazla', participate: 'Katıl', privacy: 'Gizlilik', imprint: 'Yasal', acceptCookies: 'Kabul', cookieNotice: 'Çerez kullanıyoruz.', newsletter: 'Bülten', yourEmail: 'E-posta', subscribe: 'Abone Ol', readConstitution: 'Anayasayı Oku', supportMission: 'Misyonu Destekle', spreadWord: 'Yay', joinDiscussion: 'Tartış', helpTranslate: 'Çevir', becomeAdvocate: 'Savun', educateOthers: 'Eğit', donateNow: 'Bağış Yap', getInvolved: 'Katıl', organize: 'Organize Et' },
  pl: { siteName: 'Konstytucja Światowa', tagline: 'Konstytucja dla Ludzkości', vote: 'Głosuj', yes: 'Tak', no: 'Nie', abstain: 'Wstrzymaj się', visitors: 'Odwiedzający', countries: 'Kraje', comments: 'Komentarze', languages: 'Języki', share: 'Udostępnij', download: 'Pobierz', donate: 'Darowizna', learnMore: 'Dowiedz się więcej', participate: 'Uczestnicz', privacy: 'Prywatność', imprint: 'Nota prawna', acceptCookies: 'Akceptuj', cookieNotice: 'Używamy plików cookie.', newsletter: 'Newsletter', yourEmail: 'Email', subscribe: 'Zapisz się', readConstitution: 'Czytaj Konstytucję', supportMission: 'Wesprzyj Misję', spreadWord: 'Rozpowszechnij', joinDiscussion: 'Dyskutuj', helpTranslate: 'Tłumacz', becomeAdvocate: 'Bron', educateOthers: 'Edukuj', donateNow: 'Darowizna', getInvolved: 'Zaangażuj się', organize: 'Organizuj' },
  uk: { siteName: 'Світова Конституція', tagline: 'Конституція для Людства', vote: 'Голосувати', yes: 'Так', no: 'Ні', abstain: 'Утриматися', visitors: 'Відвідувачі', countries: 'Країни', comments: 'Коментарі', languages: 'Мови', share: 'Поділитися', download: 'Завантажити', donate: 'Пожертвувати', learnMore: 'Дізнатися більше', participate: 'Брати участь', privacy: 'Приватність', imprint: 'Імпринт', acceptCookies: 'Прийняти', cookieNotice: 'Ми використовуємо файли cookie.', newsletter: 'Розсилка', yourEmail: 'Email', subscribe: 'Підписатися', readConstitution: 'Читати Конституцію', supportMission: 'Підтримати Місію', spreadWord: 'Поширити', joinDiscussion: 'Обговорити', helpTranslate: 'Перекласти', becomeAdvocate: 'Захищати', educateOthers: 'Навчати', donateNow: 'Пожертвувати', getInvolved: 'Долучитися', organize: 'Організувати' },
  id: { siteName: 'Konstitusi Dunia', tagline: 'Konstitusi untuk Kemanusiaan', vote: 'Pilih', yes: 'Ya', no: 'Tidak', abstain: 'Menyampingkan', visitors: 'Pengunjung', countries: 'Negara', comments: 'Komentar', languages: 'Bahasa', share: 'Bagikan', download: 'Unduh', donate: 'Donasi', learnMore: 'Pelajari', participate: 'Berpartisipasi', privacy: 'Privasi', imprint: 'Cetak', acceptCookies: 'Terima', cookieNotice: 'Kami menggunakan cookie.', newsletter: 'Buletin', yourEmail: 'Email', subscribe: 'Berlangganan', readConstitution: 'Baca Konstitusi', supportMission: 'Dukung Misi', spreadWord: 'Sebarkan', joinDiscussion: 'Diskusi', helpTranslate: 'Terjemahkan', becomeAdvocate: 'Advokasi', educateOthers: 'Edukasi', donateNow: 'Donasi', getInvolved: 'Terlibat', organize: 'Organisasi' },
  fa: { siteName: 'قانون اساسی جهانی', tagline: 'قانون اساسی برای بشریت', vote: 'رأی دهید', yes: 'بله', no: 'خیر', abstain: 'ممتنع', visitors: 'بازدیدکنندگان', countries: 'کشورها', comments: 'نظرات', languages: 'زبان‌ها', share: 'اشتراک‌گذاری', download: 'دانلود', donate: 'اهدا', learnMore: 'بیشتر بدانید', participate: 'مشارکت', privacy: 'حریم خصوصی', imprint: 'حقوق قانونی', acceptCookies: 'پذیرش', cookieNotice: 'ما از کوکی استفاده می‌کنیم.', newsletter: 'خبرنامه', yourEmail: 'ایمیل', subscribe: 'عضویت', readConstitution: 'خواندن قانون اساسی', supportMission: 'حمایت از ماموریت', spreadWord: 'انتشار', joinDiscussion: 'بحث', helpTranslate: 'ترجمه', becomeAdvocate: 'دفاع', educateOthers: 'آموزش', donateNow: 'اهدا', getInvolved: 'مشارکت', organize: 'سازماندهی' },
  sw: { siteName: 'Katiba ya Dunia', tagline: 'Katiba kwa Binadamu', vote: 'Piga Kura', yes: 'Ndiyo', no: 'Hapana', abstain: 'Kukaa kimya', visitors: 'Wageni', countries: 'Nchi', comments: 'Maoni', languages: 'Lugha', share: 'Shiriki', download: 'Pakua', donate: 'Changia', learnMore: 'Jifunze zaidi', participate: 'Shiriki', privacy: 'Faragha', imprint: 'Taarifa', acceptCookies: 'Kubali', cookieNotice: 'Tunatumia cookies.', newsletter: 'Jarida', yourEmail: 'Barua pepe', subscribe: 'Jiandikishe', readConstitution: 'Soma Katiba', supportMission: 'Support Mission', spreadWord: 'Sambaza', joinDiscussion: 'Jadili', helpTranslate: 'Tafsiri', becomeAdvocate: 'Tetea', educateOthers: 'Elimisha', donateNow: 'Changia', getInvolved: 'Shiriki', organize: 'Panga' },
  vi: { siteName: 'Hiến pháp Thế giới', tagline: 'Hiến pháp cho Nhân loại', vote: 'Bỏ phiếu', yes: 'Có', no: 'Không', abstain: 'Phiếu trắng', visitors: 'Khách truy cập', countries: 'Quốc gia', comments: 'Bình luận', languages: 'Ngôn ngữ', share: 'Chia sẻ', download: 'Tải xuống', donate: 'Quyên góp', learnMore: 'Tìm hiểu thêm', participate: 'Tham gia', privacy: 'Quyền riêng tư', imprint: 'Pháp lý', acceptCookies: 'Chấp nhận', cookieNotice: 'Chúng tôi sử dụng cookie.', newsletter: 'Bản tin', yourEmail: 'Email', subscribe: 'Đăng ký', readConstitution: 'Đọc Hiến pháp', supportMission: 'Hỗ trợ Sứ mệnh', spreadWord: 'Lan tỏa', joinDiscussion: 'Thảo luận', helpTranslate: 'Dịch thuật', becomeAdvocate: 'Vận động', educateOthers: 'Giáo dục', donateNow: 'Quyên góp', getInvolved: 'Tham gia', organize: 'Tổ chức' }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'de'
    const saved = localStorage.getItem('language') as Language
    return saved && translations[saved] ? saved : 'de'
  })

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage: handleSetLanguage,
      t: translations[language] || defaultTranslations,
      languageName: languageNames[language] || language
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
